# Framework for deep learning and data analysis

### Hi, my name is Te Kho, today im gonna write basic python framework for deep learning

The first step is adding **tensors** to our framework, so basically tensors are an abstruct form of vectors and matrices. Vector is one-dimensional tensor,
matrix - two-dimensional tensor and so on. **Tensor** is gonna be our base variable.

In [8]:
import numpy as np

class Tensor (object):
    
    def __init__ (self, data):
        self.data = np.array(data)

    def __add__ (self, other):
        return Tensor(self.data + other.data)

    def __repr__ (self):
        return str(self.data.__repr__())

    def __str__ (self):
        return str(self.data.__str__())

Also I added tensor operation: addition, as u can see its easy to implement other operations. *Lets try it*: 

In [9]:
x = Tensor([1,2,3,4])
y = x + x
print(y)

[2 4 6 8]


Lets implement **autograd**. Its crucial function for training our neural network. It can automatically calculate gradients.

In [18]:
import numpy as np

class Tensor (object):
    
    def __init__ (self, data, creators=None, creation_op=None):
        self.data = np.array(data)
        self.creation_op = creation_op
        self.creators = creators
        self.grad = None

    def backward (self, grad):
        self.grad = grad
        if (self.creation_op == 'add'):
            self.creators[0].backward(grad)
            self.creators[1].backward(grad)
    
    def __add__ (self, other):
        return Tensor(self.data + other.data, 
                      creators=[self, other], 
                      creation_op = 'add')
        

    def __repr__ (self):
        return str(self.data.__repr__())

    def __str__ (self):
        return str(self.data.__str__())

I added something else as u can see. **Creators** is an attribute that contains list of tenzors, that were used to create current tenzor, **creation_op** also an attribute with list of operations that we used. Basically instruction **z = x + y** creates calculating graf, with 3 knots (x, y, z) and two ribs (z->x, z->y), each of the ribs is signed with operation **"add"**. It helps to organize recursive back propogation of gradients.

In [19]:
x = Tensor([1,2,3,4,5])
y = Tensor([2,2,2,2,2])

z = x + y
z.backward(Tensor(np.array([1,1,1,1,1])))

In [20]:
print(x.grad)
print(y.grad)
print(z.creators)
print(z.creation_op)

[1 1 1 1 1]
[1 1 1 1 1]
[array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2])]
add


In [22]:
a = Tensor([1,2,3,4,5])
b = Tensor([2,2,2,2,2])
c = Tensor([5,4,3,2,1])
d = Tensor([-1,-2,-3,-4,-5])
e = a + b
f = c + d
g = e + f
g.backward(Tensor(np.array([1,1,1,1,1])))
print(a.grad)

[1 1 1 1 1]
